language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ankitind/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ankitind/docker-react yarn test -- --coverage